# conString='postgresql://postgres:[YOUR-PASSWORD]@db.qgmnqycqxvszgygazfqo.supabase.co:5432/postgres'
# conString='postgresql+psycopg2://postgres:[YOUR-PASSWORD]@[servidor]:5432/[basededatos]'
conString='postgresql+psycopg2://postgres:BuenFin2024@db.qgmnqycqxvszgygazfqo.supabase.co:5432/postgres'





#[postgres]
#user = "postgres"
#password = "5354"
#host = "localhost"
#port = 5432
#database = "amazon_data"
